#!/usr/bin/env python3
"""Generates the game's sound effects with the ElevenLabs sound API.

The game keeps its procedural WebAudio tones as a fallback, so this is a
layer on top rather than a replacement: anything missing here simply
plays the old beep. Regenerate a single sound by passing its name.

    ELEVENLABS_API_KEY=... python3 tools/build-sounds.py [name ...]

Output goes to assets/sfx/<name>.mp3 at 22 kHz / 32 kbps, which is about
2 KB a piece — small enough that all of them together are a rounding
error next to the sprite sheets in the single-file build.
"""
import json
import os
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'assets' / 'sfx'
ENDPOINT = ('https://api.elevenlabs.io/v1/sound-generation'
            '?output_format=mp3_22050_32')

# name -> (prompt, seconds, prompt_influence)
# The prompts lean hard on "dry", "short" and "no reverb": a tail that
# rings on sounds wrong under a drill that fires ten times a second, and
# the game already has its own reverb-free character.
SOUNDS = {
    'drill-hit': (
        'single short dry percussive drill bit chipping into packed dirt, '
        'tight click with a hint of grit, retro arcade sound effect, '
        'no reverb, no music, mono',
        0.5, 0.65,
    ),
    'block-break': (
        'a small block of packed earth crumbling apart, short dry crunch '
        'with falling grit, retro arcade sound effect, no reverb, no music',
        0.5, 0.6,
    ),
    'land': (
        'soft dull thud of a small animal landing on loose soil, dry, '
        'very short, retro arcade sound effect, no reverb, no music',
        0.5, 0.6,
    ),
    'pickup-air': (
        'clean bright rising chime, pressurised air canister refilling, '
        'synthetic and hopeful, short, retro arcade pickup, no music',
        0.6, 0.55,
    ),
    'pickup-loot': (
        'a handful of gold coins clinking together, bright ringing metal, '
        'loud and close, no music',
        1.0, 0.35,
    ),
    'cave-in': (
        'low ominous rumble of earth about to give way, gravel shifting '
        'and trickling, tense, no music, no voices',
        1.2, 0.6,
    ),
    'crush': (
        'heavy rocks slamming down and burying something, one dry '
        'catastrophic impact then settling debris, no music',
        1.0, 0.6,
    ),
    'suffocate': (
        'the last of the air running out, hollow descending tone going '
        'muffled and thin, bleak, no music, no voices',
        1.2, 0.55,
    ),
    'circuit-step': (
        'a heavy electrical relay switch clacking over with an electric '
        'spark, loud and close, repeated once, no music',
        1.0, 0.35,
    ),
    'circuit-fail': (
        'electrical short circuit failing, harsh buzz collapsing into a '
        'fizzle, short, no music',
        0.7, 0.65,
    ),
    'circuit-solved': (
        'electrical circuit completing, current surging through with a '
        'rising hum and a clean confirming chime, short, no music',
        1.0, 0.55,
    ),
    'vault-open': (
        'heavy steel safe door unlocking, mechanical clunk of bolts '
        'withdrawing then the door swinging open, no music, no voices',
        1.5, 0.6,
    ),
    'menu-confirm': (
        'short clean synthetic user interface confirm blip, retro arcade '
        'menu, no reverb, no music',
        0.5, 0.7,
    ),
}


def generate(name, key):
    prompt, seconds, influence = SOUNDS[name]
    body = json.dumps({
        'text': prompt,
        'duration_seconds': seconds,
        'prompt_influence': influence,
    }).encode('utf-8')
    request = urllib.request.Request(
        ENDPOINT,
        data=body,
        headers={'xi-api-key': key, 'Content-Type': 'application/json'},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        audio = response.read()
    if not audio.startswith(b'ID3') and audio[:1] != b'\xff':
        raise SystemExit(f'{name}: response is not an mp3')
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f'{name}.mp3').write_bytes(audio)
    return len(audio)


def pack():
    """Writes sounds.js, holding every mp3 as base64.

    Not fetched at runtime: a page opened over file:// cannot fetch its
    own neighbours, and the single-file build has no neighbours at all.
    Shipping the bytes inside a script sidesteps both, and keeps local
    play identical to what the published build does.
    """
    import base64
    entries = []
    for path in sorted(OUT.glob('*.mp3')):
        b64 = base64.b64encode(path.read_bytes()).decode('ascii')
        entries.append(f"    '{path.stem}': '{b64}',")
    body = '\n'.join(entries)
    (ROOT / 'sounds.js').write_text(
        '// Generated by tools/build-sounds.py — do not edit by hand.\n'
        '// Base64 mp3, decoded once the audio context is unlocked.\n'
        'const SFX_DATA = Object.freeze({\n'
        f'{body}\n'
        '});\n',
        encoding='utf-8',
    )
    size = (ROOT / 'sounds.js').stat().st_size
    print(f'packed {len(entries)} sounds into sounds.js ({size / 1024:.0f} KB)')


def main():
    if '--pack-only' in sys.argv:
        pack()
        return

    key = os.environ.get('ELEVENLABS_API_KEY')
    if not key:
        raise SystemExit('set ELEVENLABS_API_KEY')

    wanted = sys.argv[1:] or list(SOUNDS)
    unknown = [name for name in wanted if name not in SOUNDS]
    if unknown:
        raise SystemExit(f'unknown sound(s): {", ".join(unknown)}')

    total = 0
    for name in wanted:
        try:
            size = generate(name, key)
        except urllib.error.HTTPError as error:
            raise SystemExit(f'{name}: HTTP {error.code} {error.read()[:200]}')
        total += size
        print(f'{name:16} {size / 1024:5.1f} KB')
    print(f'\n{len(wanted)} sounds · {total / 1024:.0f} KB total')
    pack()


if __name__ == '__main__':
    main()
